// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKH9e4pNfsO-DOpWh4yq5f6B2T9nmj5eE',
    appId: '1:531888707010:web:ca4de132cf5d090e0fb25b',
    messagingSenderId: '531888707010',
    projectId: 'student-attendance-syste-54136',
    authDomain: 'student-attendance-syste-54136.firebaseapp.com',
    storageBucket: 'student-attendance-syste-54136.firebasestorage.app',
    measurementId: 'G-SWTP9NPCCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKGn00KQe6tQCJt7k_1xPLol9abP8ZCZs',
    appId: '1:531888707010:android:c719f23ba0464d560fb25b',
    messagingSenderId: '531888707010',
    projectId: 'student-attendance-syste-54136',
    storageBucket: 'student-attendance-syste-54136.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3d-WUesCEnW5wParlRyfhRPDM8im5sqg',
    appId: '1:531888707010:ios:06bcc329a36febcf0fb25b',
    messagingSenderId: '531888707010',
    projectId: 'student-attendance-syste-54136',
    storageBucket: 'student-attendance-syste-54136.firebasestorage.app',
    iosBundleId: 'com.example.studentAttendanceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3d-WUesCEnW5wParlRyfhRPDM8im5sqg',
    appId: '1:531888707010:ios:06bcc329a36febcf0fb25b',
    messagingSenderId: '531888707010',
    projectId: 'student-attendance-syste-54136',
    storageBucket: 'student-attendance-syste-54136.firebasestorage.app',
    iosBundleId: 'com.example.studentAttendanceSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKH9e4pNfsO-DOpWh4yq5f6B2T9nmj5eE',
    appId: '1:531888707010:web:553c9434036fb8a40fb25b',
    messagingSenderId: '531888707010',
    projectId: 'student-attendance-syste-54136',
    authDomain: 'student-attendance-syste-54136.firebaseapp.com',
    storageBucket: 'student-attendance-syste-54136.firebasestorage.app',
    measurementId: 'G-5B4D6F7GTQ',
  );
}
